### ISSUE TITLE
Issue if tick rollover occurs while waiting for flash (from the forum)

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/stm32g0xx_hal_driver#1]
https://github.com/STMicroelectronics/stm32g0xx_hal_driver/blob/84a2e9393d6761802b70a4424e3049b9f3e51a22/Src/stm32g0xx_hal_flash.c#L596

Please see https://community.st.com/s/question/0D53W00001yhRP0SAM/issue-if-tick-rollover-occurs-while-waiting-for-flash
and fix.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 149113

**Comment by TOUNSTM** [comment]
Fixed in commit [272438f](https://github.com/STMicroelectronics/stm32g0xx_hal_driver/commit/272438fbdb3180e5d78c0f25608045af31528383)
