### ISSUE TITLE
HAL_GPIO_EXTI_Callback missing from STM32G0 HAL GPIO API

### ISSUE THREAD

**Issue by insolace** [STMicroelectronics/stm32g0xx_hal_driver#7]
Ali Labbene requested that I open a new issue here in this thread:
https://github.com/STMicroelectronics/STM32CubeG0/issues/7#issuecomment-2491193412

The STM32G0 HAL library does not include the standard HAL GPIO external interrupt callback. This is what we would expect:

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
}

Instead, STM32G0 only includes HAL_GPIO_EXTI_Rising_Callback() and HAL_GPIO_EXTI_Falling_Callback(). These functions are fine, but HAL_GPIO_EXTI_Callback is the standard API that is used with most (if not all) other STM32 HAL drivers, and if you google any "how to make an stm32 respond to GPIO" tutorial / walk through, HAL_GPIO_EXTI_Callback is the method that is shown.

How To Reproduce:

Compare stm32g0xx_hal_gpio.h in this repository to to https://github.com/STMicroelectronics/stm32f4xx-hal-driver/blob/master/Inc/stm32f4xx_hal_gpio.h and you will see the API method in question is missing in STM32G0.

**Comment by TOUNSTM** [comment]
Hello @insolace,

Thank you for your contribution. This change is actually a new feature that enhances the functionality of the STM32G0 HAL library. By distinguishing between rising and falling edge interrupts.
To implement this new feature, it was necessary to break compatibility with the previous single callback method. The reason for this is that there is a single entry point for the HAL GPIO interrupt service routine: `HAL_GPIO_EXTI_IRQHandler()`. It is not feasible to support both the legacy single callback method and the new dual callback method within this single entry point.

As a result, you will need to adapt your code to align with the new implementation. By doing so, you will be able to take full advantage of the new hardware capabilities.

Thank you for your understanding and cooperation.
Best Regards,
